"""empty message

Revision ID: 418a4ce025da
Revises: 3d3ce9593fe3
Create Date: 2022-06-15 00:02:55.140730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418a4ce025da'
down_revision = '3d3ce9593fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sobrenome', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sobrenome')
    # ### end Alembic commands ###
