"""empty message

Revision ID: 6166951f82f9
Revises: 82b3ddfbc52f
Create Date: 2022-06-05 00:00:58.015700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6166951f82f9'
down_revision = '82b3ddfbc52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('perm', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'perm')
    # ### end Alembic commands ###
