"""empty message

Revision ID: 73b56bbab527
Revises: e3a2fbd04039
Create Date: 2022-06-13 00:09:57.953121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b56bbab527'
down_revision = 'e3a2fbd04039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'senha_hash')
    # ### end Alembic commands ###
