"""empty message

Revision ID: e3a2fbd04039
Revises: 6166951f82f9
Create Date: 2022-06-12 23:48:58.946713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3a2fbd04039'
down_revision = '6166951f82f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('padrao', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_roles_padrao'), 'roles', ['padrao'], unique=False)
    op.drop_column('roles', 'perm')
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('roles', sa.Column('perm', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_roles_padrao'), table_name='roles')
    op.drop_column('roles', 'padrao')
    # ### end Alembic commands ###
