"""empty message

Revision ID: e8e69e50e6e9
Revises: 418a4ce025da
Create Date: 2022-06-15 01:30:29.322903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8e69e50e6e9'
down_revision = '418a4ce025da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
